spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5434/fixa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.fixa: DEBUG
